### ISSUE TITLE
GTK Program crashes after pressing a button

### ISSUE THREAD

**Issue by pharaone** [AlanGriffiths/egmde#3] opened 2018-04-01 10:33 UTC
While using gedit and gnome-system-monitor i found out that if you press the buttons that open a "child window" the program crashes and you can only close it, here there is the gif:
![ciao](https://user-images.githubusercontent.com/17162630/38172233-c9d5783e-35a8-11e8-86dc-8f54336e6781.gif)

**Comment by AlanGriffiths** [comment] 2018-04-01 10:58
This looks like a Mir issue, not egmde. The Mir xdg-shell support is a work-in-progress and I think this is one of the "known gaps" (that will be addressed in the next Mir release). @wmww WDYT?

**Comment by AlanGriffiths** [comment] 2018-04-01 13:10
It just occurred to me: it may be worth trying the 0.31.1 bugfix release (this isn't in the bionic archive yet):

    $ sudo add-apt-repository ppa:mir-team/release
    $ sudo apt update
    $ sudo apt upgrade -y

**Comment by pharaone** [comment] 2018-04-01 13:31
just tried with 0.31.1, the problem is still here

**Comment by wmww** [comment] 2018-04-01 16:29
It's a known issue. Currently, subsurfaces can not receive input, which I believe may be the cause. Regardless of if that's true or not, it will get fixed as I complete support for subsurfaces (my current priority).

**Comment by AlanGriffiths** [comment] 2018-04-27 15:09
This has just been fixed in Mir development. Once the PPA updates (about 30min) you can try it out with ppa:mir-team/dev:
```
$ sudo apt-add-repository ppa:mir-team/dev
$ sudo apt update
$ sudo apt upgrade
```

**Closed** 2018-04-29 07:45 UTC
Labels: Mir Wayland bug
